spring:
   datasource:
      primary:
         url: jdbc:mysql://127.0.0.1:3306/jeecf?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
         username: root
         password: 12345678
         
redis:
   host: 127.0.0.1
   port: 6379
   maxTotal: 100
   maxIdle: 30
   maxWaitMillis: 6000
   testWhileIdle: true
   timeBetweenEvictionRunsMillis: 30000
   minEvictableIdleTimeMillis: 1800000
   
file:
   plugin:
      upload:
         path: ${HOME}/jeecf/plugin/real
         tmp: 
            path: ${HOME}/jeecf/plugin/tmp
      suffix: jar
   tmpl:
      download:
         prefix:
            path: ${HOME}/jeecf/tmpl/download
      upload:
         path: ${HOME}/jeecf/tmpl/real
         tmp:
            path: ${HOME}/jeecf/tmpl/tmp
      suffix: zip   
      
encrypt:
   key: 12345678   